// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO18GkYD2ppvafJaK_4ZjI1GIR6__Y6qU',
    appId: '1:490267905091:web:0a59d6f8d8b9b699cfd8f6',
    messagingSenderId: '490267905091',
    projectId: 'first---app',
    authDomain: 'first---app.firebaseapp.com',
    storageBucket: 'first---app.appspot.com',
    measurementId: 'G-TW1N7578BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBB7SiY9pbMSojErkSjSf66aVTH-_FteE',
    appId: '1:490267905091:android:fa711899d3dd6743cfd8f6',
    messagingSenderId: '490267905091',
    projectId: 'first---app',
    storageBucket: 'first---app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVNfK-z6EWCDZ5m7iPqC8k3VRz_yGFdfQ',
    appId: '1:490267905091:ios:e3e504bf1d7ecdb1cfd8f6',
    messagingSenderId: '490267905091',
    projectId: 'first---app',
    storageBucket: 'first---app.appspot.com',
    iosBundleId: 'com.example.temTechnologies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVNfK-z6EWCDZ5m7iPqC8k3VRz_yGFdfQ',
    appId: '1:490267905091:ios:be4979b028a64e69cfd8f6',
    messagingSenderId: '490267905091',
    projectId: 'first---app',
    storageBucket: 'first---app.appspot.com',
    iosBundleId: 'com.example.temTechnologies.RunnerTests',
  );
}
